# Runs Redmine Backlogs with PostgreSQL database
version: '2'
services:
  ldap:
    extends:
      file: ../mail/docker-compose.yml
      service: ldap
  mail:
    extends:
      file: ../mail/docker-compose.yml
      service: mail
    environment:
      TRUSTED_NETWORKS: 'true'
  postgres:
    extends:
      file: ../postgres/docker-compose.yml
      service: postgres
    environment:
      PG_USER_ROUNDCUBE: "${ROUNDCUBE_POSTGRES_PASSWORD}"
  roundcube:
    image: algorythm/roundcube:latest
    hostname: webmail.algorythm.de
    environment:
      DB_TYPE: pgsql
      DB_USERNAME: roundcube
      DB_PASSWORD: "${ROUNDCUBE_POSTGRES_PASSWORD}"
      RC_ENABLE_INSTALLER: 'false'
    ports:
      - "9000:9000"
    volumes:
      - "../ca/ssl/certs/cacert.pem:/etc/ssl/certs/cacert.pem"
#    depends_on:
#      - postgres
#      - mail
#    links:
#      - postgres
#      - mail
