version: '2'
services:
  consul:
    image: gliderlabs/consul-server:latest
    hostname: consul
    command: "-server -bootstrap-expect 1 -ui"
    ports:
     - "8500:8500" # consul web UI & REST service
     - "8400:8400" # consul RPC
     - "53:8600/udp" # consul DNS
  registrator:
    image: gliderlabs/registrator:latest
    command: "consul://consul:8500"
    volumes:
     - "/var/run/docker.sock:/tmp/docker.sock"
    depends_on:
     - consul
    links:
     - "consul"
  apacheds:
    image: algorythm/apacheds:latest
    hostname: auth.algorythm.de
    depends_on:
     - consul
    cap_add:
     - NET_BIND_SERVICE
    ports:
     - "389:10389" # LDAP port
    links:
     - "consul"
  mail:
    image: algorythm/mail:latest
    hostname: mail.algorythm.de
    ports:
     - "25:25"
     - "465:465"
     - "587:587"
     - "110:110"
     - "143:143"
     - "993:993"
     - "995:995"
    depends_on:
     - consul
    links:
     - "consul"
