version: '2'
services:
  consul:
    extends:
      file: common.yml
      service: consul
#    volumes:
#      - "./data/consul:/consul/data"
  registrator:
    extends:
      file: common.yml
      service: registrator
    depends_on:
      - consul
    links:
      - consul
  elasticsearch:
    extends:
      file: common.yml
      service: elasticsearch
  logstash:
    extends:
      file: common.yml
      service: logstash
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
  kibana:
    extends:
      file: common.yml
      service: kibana
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
  ldap:
    extends:
      file: 389ds/docker-compose.yml
      service: ldap
    environment:
      SYSLOG_REMOTE_ENABLED: "true"
      SYSLOG_HOST: "logstash"
      SYSLOG_PORT: 10514
      LDAP_USER_DN_REDMINE: "${REDMINE_LDAP_USER_DN}"
      LDAP_USER_PW_REDMINE: "${REDMINE_LDAP_USER_PW}"
#    volumes:
#      - "./data:/var/lib/dirsrv"
    depends_on:
      - logstash
    links:
      - logstash
  # TODO: fix mail integration of logstash (parser,connection) and ldap (user+password)
  mail:
    extends:
      file: mail/docker-compose.yml
      service: mail
    environment:
      SYSLOG_REMOTE_ENABLED: "true"
      SYSLOG_HOST: "logstash"
      SYSLOG_PORT: 10514
    depends_on:
      - logstash
    links:
      - logstash
  postgres:
    extends:
      file: postgres/docker-compose.yml
      service: postgres
    environment:
      SYSLOG_REMOTE_ENABLED: "true"
      SYSLOG_HOST: "logstash"
      SYSLOG_PORT: 10514
      PG_USER_REDMINE: "${REDMINE_POSTGRES_PASSWORD}"
    depends_on:
      - logstash
    links:
      - logstash
  redmine:
    extends:
      file: redmine/docker-compose.yml
      service: redmine
    environment:
      SYSLOG_REMOTE_ENABLED: "true"
      SYSLOG_HOST: "logstash"
      SYSLOG_PORT: 10514
    depends_on:
      - postgres
    links:
      - postgres
