version: '2'
services:
  consul:
    image: consul:v0.6.4
    hostname: consul
    command: "agent -server -bootstrap-expect 1 -ui"
    ports:
      - "8500:8500" # consul web UI & REST service
      - "8400:8400" # consul RPC
      - "53:8600/udp" # consul DNS
    environment:
      CONSUL_CLIENT_INTERFACE: eth0
#    volumes:
#      - "$PWD/data/consul:/consul/data"
  registrator:
    image: gliderlabs/registrator:v7
    command: "consul://consul:8500"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
    depends_on:
      - consul
    links:
      - consul
  elasticsearch:
    image: elasticsearch:5
    hostname: elasticsearch
    environment:
      LOGSPOUT: ignore
    volumes:
      - "$PWD/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
  logstash:
    image: logstash:5
    hostname: logstash
    command: "./wait-for-tcp-port.sh elasticsearch 9200 logstash -f /config/logstash.conf"
    environment:
      LOGSPOUT: ignore
    volumes:
      - "$PWD/logstash:/config"
      - "$PWD/scripts/wait-for-tcp-port.sh:/wait-for-tcp-port.sh"
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
  kibana:
    image: kibana:5
    command: "./wait-for-tcp-port.sh elasticsearch 9200 kibana -e http://elasticsearch:9200"
    volumes:
      - "$PWD/scripts/wait-for-tcp-port.sh:/wait-for-tcp-port.sh"
    ports:
      - "5601:5601" # Kibana web UI
    environment:
      LOGSPOUT: ignore
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
  logspout:
    image: gliderlabs/logspout:v3
    command: "syslog://logstash:5000"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
    environment:
      LOGSPOUT: ignore
    depends_on:
      - logstash
    links:
      - logstash
  apacheds:
    image: algorythm/apacheds:latest
    hostname: auth.algorythm.de
    depends_on:
      - consul
    cap_add:
      - NET_BIND_SERVICE
    ports:
      - "389:10389" # LDAP port
    links:
      - consul
  mail:
    image: algorythm/mail:latest
    hostname: mail.algorythm.de
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
      - "110:110"
      - "143:143"
      - "993:993"
      - "995:995"
    depends_on:
      - consul
    links:
      - consul
