version: '2'
services:
  consul:
    image: algorythm/consul:latest
    hostname: consul.algorythm.de
    command: "/entrypoint-consul.sh server -bootstrap-expect 1 -ui"
    ports:
     - "8500:8500" # consul web UI
     - "53:8600/udp" # consul DNS
    env_file:
     - consul/consul.env
  apacheds:
    image: algorythm/apacheds:latest
    hostname: auth.algorythm.de
    depends_on:
     - consul
    ports:
     - "389:10389" # LDAP port
    links:
     - "consul"
  mail:
    image: algorythm/mail:latest
    hostname: mail.algorythm.de
    depends_on:
     - consul
    links:
     - "consul"
