version: '2'
services:
  consul:
    extends:
      file: common.yml
      service: consul
#    volumes:
#      - "./data/consul:/consul/data"
  registrator:
    extends:
      file: common.yml
      service: registrator
    depends_on:
      - consul
    links:
      - consul
  elasticsearch:
    extends:
      file: common.yml
      service: elasticsearch
  logstash:
    extends:
      file: common.yml
      service: logstash
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
  kibana:
    extends:
      file: common.yml
      service: kibana
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
  logspout:
    extends:
      file: common.yml
      service: logspout
    depends_on:
      - logstash
    links:
      - logstash
  apacheds:
    extends:
      file: apacheds/docker-compose.yml
      service: apacheds
  mail:
    extends:
      file: mail/docker-compose.yml
      service: mail
    environment:
      LOGSTASH_ENABLED: "true"
  postgres:
    extends:
      file: common.yml
      service: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PG_USER_REDMINE: "${REDMINE_POSTGRES_PASSWORD}"
  redmine:
    extends:
      file: redmine/docker-compose.yml
      service: redmine
    depends_on:
      - postgres
    links:
      - postgres
