# Runs Redmine Backlogs with PostgreSQL database
version: '2'
services:
  ldap:
    extends:
      file: ../389ds/docker-compose.yml
      service: ldap
    environment:
      LDAP_USER_DN_REDMINE: "${REDMINE_LDAP_USER_DN}"
      LDAP_USER_PW_REDMINE: "${REDMINE_LDAP_USER_PW}"
#    volumes:
#      - "./data:/var/lib/dirsrv"
  postgres:
    extends:
      file: ../postgres/docker-compose.yml
      service: postgres
    environment:
      PG_USER_REDMINE: "${REDMINE_POSTGRES_PASSWORD}"
  redmine:
    image: algorythm/redmine-backlogs:latest
    build: .
    hostname: redmine.algorythm.de
    environment:
      INSTALL_BACKUP_FILE: /backup/redmine-bak-public.tar.bz2
      DB_ADAPTER: "postgresql"
      DB_USERNAME: redmine
      DB_PASSWORD: "${REDMINE_POSTGRES_PASSWORD}"
      LDAP_AUTH: "ldap-default"
      LDAP_USER_DN: "${REDMINE_LDAP_USER_DN}"
      LDAP_USER_PW: "${REDMINE_LDAP_USER_PW}"
    ports:
      - "3000:3000"
    volumes:
       - "./work:/backup"
#      - "./data:/redmine/files"
#    depends_on:
#      - postgres
#      - ldap
#    links:
#      - postgres
#      - ldap
