# Runs Redmine Backlogs with PostgreSQL database
version: '2'
services:
  ldap:
    extends:
      file: ../389ds/docker-compose.yml
      service: ldap
    environment:
      LDAP_USER_DN_REDMINE: "${REDMINE_LDAP_USER_DN}"
      LDAP_USER_PW_REDMINE: "${REDMINE_LDAP_USER_PW}"
#    volumes:
#      - "./data:/var/lib/dirsrv"
  postgres:
    extends:
      file: ../postgres/docker-compose.yml
      service: postgres
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      PG_USER_REDMINE: "${REDMINE_POSTGRES_PASSWORD}"
  redmine:
    image: algorythm/redmine-backlogs:latest
    hostname: redmine.algorythm.de
    environment:
      POSTGRES_PORT_5432_TCP: "true"
      POSTGRES_ENV_POSTGRES_USER: redmine
      POSTGRES_ENV_POSTGRES_PASSWORD: "${REDMINE_POSTGRES_PASSWORD}"
      LDAP_AUTH: "ldap-default"
      LDAP_USER_DN: "${REDMINE_LDAP_USER_DN}"
      LDAP_USER_PW: "${REDMINE_LDAP_USER_PW}"
    ports:
      - "3000:3000"
#    depends_on:
#      - postgres
#    links:
#      - postgres
