version: '2'
services:
  elasticsearch:
    extends:
      file: ../common.yml
      service: elasticsearch
  logstash:
    extends:
      file: ../common.yml
      service: logstash
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
  kibana:
    extends:
      file: ../common.yml
      service: kibana
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
  ldap:
    image: algorythm/389ds:latest
    hostname: ldap.algorythm.de
    environment:
      LOGSTASH_ENABLED: "true"
    ports:
      - "389:389"
    depends_on:
      - logstash
    links:
      - logstash
#    volumes:
#      - "./data:/var/lib/dirsrv"
