version: '2'
services:
  elasticsearch:
    extends:
      file: ../common.yml
      service: elasticsearch
  logstash:
    extends:
      file: ../common.yml
      service: logstash
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
  kibana:
    extends:
      file: ../common.yml
      service: kibana
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
#  mail:
#    extends:
#      file: ../mail/docker-compose.yml
#      service: mail
#    environment:
#      LDAP_STARTUP_CHECK_ENABLED: 'false'
#      SYSLOG_REMOTE_ENABLED: "true"
#      SYSLOG_HOST: "logstash"
#      SYSLOG_PORT: 1025
  postgres:
    extends:
      file: ../postgres/docker-compose.yml
      service: postgres
    environment:
      SYSLOG_REMOTE_ENABLED: "true"
      SYSLOG_HOST: "logstash"
      SYSLOG_PORT: 10514
#  redmine:
#    image: algorythm/redmine-backlogs:latest
#    hostname: redmine.algorythm.de
#    ports:
#      - "3000:3000"
#    environment:
#      SYSLOG_REMOTE_ENABLED: "true"
#      SYSLOG_HOST: "logstash"
#      SYSLOG_PORT: 10514
#  ldap:
#    image: algorythm/389ds:latest
#    hostname: ldap.algorythm.de
#    environment:
#      LOGSTASH_ENABLED: "true"
#    ports:
#      - "389:389"
#    depends_on:
#      - logstash
#    links:
#      - logstash
#    volumes:
#      - "./data:/var/lib/dirsrv"
