version: '2'
services:
  ldap:
    image: algorythm/389ds:latest
    hostname: ldap.algorythm.de
    ports:
      - "389:389"
    environment:
      LDAP_ROOT_DN_PWD: "${LDAP_ROOT_DN_PWD}"
      LDAP_INSTALL_BACKUP_FILE: "/backup/ldap-bak.tar.bz2"
    volumes:
      - "./work:/backup"
#      - "./data:/var/lib/dirsrv"
