# Runs Redmine Backlogs with PostgreSQL database
version: '2'
services:
  ldap:
    extends:
      file: ../389ds/docker-compose.yml
      service: ldap
    environment:
      LDAP_USER_DN_NGINX: "${NGINX_LDAP_USER_DN}"
      LDAP_USER_PW_NGINX: "${NGINX_LDAP_USER_PW}"
  nginx:
    image: algorythm/nginx:latest
    hostname: web.algorythm.de
    environment:
#      VHOST_TEST_NAME: "test.algorythm.de"
#      VHOST_TEST_PROXY_PASS: "http://ldap/"
      LDAP_ENABLED: "true"
      LDAP_BIND_DN: "${NGINX_LDAP_USER_DN}"
      LDAP_BIND_PW: "${NGINX_LDAP_USER_PW}"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "../ssl/private/mail.algorythm.de.key:/etc/nginx/ssl/private/mail.algorythm.de.key"
      - "../ssl/certs/mail.algorythm.de.pem:/etc/nginx/ssl/certs/mail.algorythm.de.pem"
      - "./ssl/web.key:/etc/ssl/private/server.key"
      - "./ssl/web.pem:/etc/ssl/certs/server.pem"
#    depends_on:
#      - ldap
#    links:
#      - ldap
