version: '2'
services:
  elasticsearch:
    image: elasticsearch:5
    hostname: elasticsearch
    environment:
      LOGSPOUT: ignore
    volumes:
      - "$PWD/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
  logstash:
    image: logstash:5
    hostname: logstash
    command: "./wait-for-tcp-port.sh elasticsearch 9200 logstash -f /config/logstash.conf"
    environment:
      LOGSPOUT: ignore
    volumes:
      - "$PWD/logstash:/config"
      - "$PWD/scripts/wait-for-tcp-port.sh:/wait-for-tcp-port.sh"
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
  kibana:
    image: kibana:5
    command: "./wait-for-tcp-port.sh elasticsearch 9200 kibana -e http://elasticsearch:9200"
    volumes:
      - "$PWD/scripts/wait-for-tcp-port.sh:/wait-for-tcp-port.sh"
    ports:
      - "5601:5601" # Kibana web UI
    environment:
      LOGSPOUT: ignore
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
  logspout:
    image: gliderlabs/logspout:v3
    command: "syslog://logstash:5000"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
    environment:
      LOGSPOUT: ignore
    depends_on:
      - logstash
    links:
      - logstash
