version: '2'
services:
  logstash:
    image: logstash:5
    hostname: logstash
    command: "logstash -f /config/logstash.conf"
    ports:
      - "10389:10389"
    volumes:
      - "../../logstash.conf:/config/logstash.conf"
