version: '2'
services:
  mail:
    image: algorythm/mail:latest
    hostname: mail.algorythm.de
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
      - "110:110"
      - "143:143"
      - "993:993"
      - "995:995"
